Fix Cygwin compilation and miscellaneous fixes and tweaks
MegaByte/lighterjson pull request #1
Opened 2019-04-24 21:17 UTC by AlexTMjugador

This PR allows the code to be compiled under a Cygwin-based toolchain, namely i686-w64-mingw32-gcc. Moreover, it also removes dependencies on not standard integer types, improves error messages showed by the do_file function, always closes the file descriptors that function opens and fixes some Makefile parsing errors arising from not using TAB. Some printf format specificators were changed in order to be more cross-platform, too.

2019-04-24 21:19 UTC, AlexTMjugador commented
To compile under Cygwin, I used the following commands:
```
$ git config --global core.autocrlf input
$ git clone --depth=1 https://github.com/witwall/mman-win32.git sys
$ cd sys
$ git reset --hard 9f115ad0b4c03e9356f5dd596deda0da6729a257
$ ./configure
$ make libmman.a && cd .. && i686-w64-mingw32-gcc -s -Ofast -Wall -I. -Lsys -lmman -o lighterjson.exe lighterjson.c sys/mman.c
```

Cygwin toolchain version:
```
$ i686-w64-mingw32-gcc -v
gcc version 7.4.0 (GCC)
```

I've also compiled it succesfully under a standard, Debian GCC 8 compiler.

2019-08-03 17:03 UTC, AlexTMjugador commented
As some time has passed, I'm curious about whether there are any plans to merge this PR?

2020-12-23 00:36 UTC, MegaByte commented
Hi @AlexTMjugador,
Sorry, I missed notifications about your PR. I will take a look now.

2020-12-23 02:01 UTC, MegaByte requested changes

2020-12-23 02:01 UTC, MegaByte commented on src/lighterjson.c
> +      closedir(dir);
This stops processing upon the first file error, which is not the behavior I intended.

2020-12-23 19:54 UTC, MegaByte commented
Hi @AlexTMjugador,
Thanks for your PR. I ran some tests of your changes under MacOS, and it completely breaks the parsing. I'm not sure yet what is going wrong, but it looks like the pointers are not being moved around appropriately, resulting in corrupted files. I cannot merge this as-is.

2020-12-23 20:00 UTC, MegaByte commented on src/lighterjson.c
> +  file.data_start = mmap(NULL, sb.st_size, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
It looks like this change is causing the file to not be altered, as by mmap definition, the underlying file is not modified. This must be reverted in order for the program to function.

2020-12-30 13:38 UTC, AlexTMjugador commented
Thanks for the review, I totally forgot about this!

Right now I'm kinda busy, but I expect to be able to address your comments within January or February.

2021-06-02 05:56 UTC, merged

2021-06-08 17:02 UTC, AlexTMjugador commented on src/lighterjson.c
> +      closedir(dir);
I intended not to change that behavior, but `d_type` is not a standard field in the entry struct. The most standard-compliant way I know of getting whether the file is a folder or not for this involves calling `stat`, which can indeed fail and stop the processing. However, the `readdir` call above will also return `NULL` if an error happens, so the processing will be effectively stopped if an errors occurs during that call anyway. I don't think this change has many practical implications.

2021-06-08 17:02 UTC, AlexTMjugador commented on src/lighterjson.c
> +  file.data_start = mmap(NULL, sb.st_size, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
I changed it to `MAP_PRIVATE` because it felt safer to not propagate changes that other processes may do to the file, but you're totally right that another effect of that flag is that the file won't be updated, which makes it useless for this use case. My bad for not noticing that before.

2021-06-08 17:02 UTC, AlexTMjugador commented
In the end I forgot about this PR again, sorry 😅 

Anyway, I'm glad you could merge this and tweak that `mmap` flag to better suit your needs! For the record, I left some comments on your review.